### ISSUE TITLE
Use Case 10: Demo Preparation

### ISSUE THREAD

**Issue by arilloid** [ktageja/DataSense-PRJ666-team-5#13]
# Demo Preparation

## User Story

As members of the team 5, we want to prepare the demo for showcasing our development progress after Sprint 1.

## Description

This use case involves preparing for the project progress demonstration after completing Sprint 1.

The demo is needed to demonstrate the system's capabilities to the stakeholders after the first sprint. The demo should clearly show how sensor data is sent from the Raspberry Pi to the server and how the frontend retrieves and displays this data in the form of a dashboard.

## Acceptance Criteria

- [ ] All of the Sprint's objectives are achieved and ready to be demonstrated.
- [ ]  The demo environment is set up, with all components (Raspberry Pi, backend server, and frontend application) properly configured.
- [ ]  A detailed demo outline is prepared, covering all aspects of the implemented functionality.
- [ ]  A rehearsal of the demo is conducted, and any potential issues are identified and addressed.

### Normal Flow of Events

The team achieves all of the Sprint's objectives. 
Each team member hoes over the acceptance criteria and performs the necessary tests for the use cases they are responsible for.
The team verifies that the system works as expected (the data is transmitted from the Raspberry PI, processed in the server and properly displayed on the dashboard).
The team prepares the demo outline. 
The team rehearses the demo and is ready to perform in front of the stakeholder. 

#### S-1:   The team is unable to achieve some of the sprint's objectives.
Team lead reaches out to the professor to explain the situation. 
Team performs the demo without one of the listed features (with possible mark deductions).

**Comment by ohodovaniuk1** [comment]
Sprint 1 Demo Completed

We have successfully achieved all tasks for Sprint 1, which include:

Setting up the Raspberry Pi hardware.
Configuring and connecting sensors to transmit raw data.
Sending sensor data from the Raspberry Pi to the cloud.
Implementing a UI dashboard to display the collected data in real-time.

The demo video showcasing these accomplishments has been prepared and can be reviewed for further feedback.
