### ISSUE TITLE
Use Case 22: Improve UI Responsiveness for Dashboard

### ISSUE THREAD

**Issue by ktageja** [ktageja/DataSense-PRJ666-team-5#25]
#    Improve UI Responsiveness for Dashboard
## User Story
As a user, I want the dashboard to be responsive and accessible on both desktop and mobile devices so that I can easily monitor my sensor data from any device.

## Description
This use case involves improving the responsiveness of the dashboard to ensure it works smoothly on a variety of devices, including desktops, tablets, and mobile phones. The dashboard should dynamically adjust to different screen sizes and resolutions, ensuring a consistent user experience across devices.
## Acceptance Criteria

- [ ] The dashboard is fully responsive and works on desktop, tablet, and mobile devices.
- [ ] Layouts, graphs, and tables adjust dynamically based on screen size and resolution.
- [ ] The dashboard maintains usability and readability across all devices.
- [ ] Frontend components are tested for responsiveness.

### Normal Flow of Events
The frontend team tests the dashboard on various devices and screen sizes (e.g., desktop, tablet, mobile).
The layout dynamically adjusts, and all components (graphs, tables, buttons) remain functional and accessible.
No layout issues or display problems are encountered on different screen resolutions..
#### S-1: Layout issues on certain devices
The dashboard components (graphs, tables) do not display correctly on certain screen sizes or devices.
The frontend team adjusts the CSS and layout to ensure a consistent experience across all devices.

**Comment by zhifenli** [comment]
The dashboard is fully responsive and works on desktop, tablet, and mobile devices. The dashboard maintains usability and readability across all devices. Frontend components are tested for responsiveness.
