### ISSUE TITLE
Use Case 3: Set Up Raspberry Pi and Connect Sensors

### ISSUE THREAD

**Issue by ktageja** [ktageja/DataSense-PRJ666-team-5#5]
## User Story
As a hardware developer, I want to set up the Raspberry Pi and connect the sensors so that I can read data from the temperature, humidity, and soil moisture sensors.

## Description

This use case describes the setup of the Raspberry Pi Pico W and its connection to sensors (DHT11 for temperature/humidity and Soil Moisture sensor).

Proper sensor connection and setup of the Raspberry Pi is crucial to collect data from the sensors for the project.

## Acceptance Criteria

- [ ] Raspberry Pi is connected to the sensors and properly powered on.
- [ ]  Data is read from the temperature, humidity, and soil moisture sensors without errors.
- [ ]  The sensor data is output in a readable format (e.g., console).

#  Testing

## Normal Flow of Events

Connect the DHT11 temperature/humidity sensor and Soil Moisture sensor to the Raspberry Pi.
Install the necessary drivers and libraries on the Raspberry Pi.
Test the connection by running simple scripts to ensure the sensors are providing valid data.
Confirm that the sensors are functioning correctly.

### S-1: Hardware connection errors (e.g., faulty wiring)

Raspberry Pi fails to read data due to incorrect sensor wiring.
Developer checks and fixes the wiring.

### S-2:  Driver or library incompatibility
Incompatible sensor drivers prevent the Raspberry Pi from reading sensor data.
Developer installs compatible drivers or libraries.

**Comment by ohodovaniuk1** [comment]
We have successfully completed the setup of the Raspberry Pi Pico W and connected the DHT11 temperature/humidity sensor and the Soil Moisture sensor.

Key Achievements:

The Raspberry Pi is powered on and connected to the sensors.
Data is being read from the temperature, humidity, and soil moisture sensors without errors.
Sensor data is displayed in a readable format via the console.
Testing Outcomes:

Sensors were tested, and data is being transmitted as expected.
