### ISSUE TITLE
Use Case 6: Basic UI for Viewing Live Sensor Data

### ISSUE THREAD

**Issue by ktageja** [ktageja/DataSense-PRJ666-team-5#8]
# Basic UI for viewing live sensor data

## User Story
As a user, I want to view live sensor data on the dashboard so that I can monitor environmental conditions.

## Description
This use case describes the implementation of a user interface that displays live sensor data.
Sensor data must be displayed in real-time to allow users to monitor the environment.

## Acceptance Criteria

- [ ] Live sensor data is displayed on the dashboard.
- [ ]  Data includes temperature, humidity, and soil moisture levels.
- [ ]  Data refreshes every X seconds (e.g., 10 seconds).
- [ ]  UI is responsive across different devices and browsers.

### Normal Flow of Events
The user logs into their account.
The system retrieves the latest sensor data from the backend.
The system displays the temperature, humidity, and soil moisture data on the dashboard in real-time.

#### S-1:  UI fails to update
The user interface fails to refresh the sensor data due to a backend error.
The system displays a “Data not available” message and retries.

#### S-2:  Display issues on different devices or browsers
The dashboard fails to display properly on mobile or different browsers.
Developers troubleshoot UI responsiveness issues.

**Comment by zhifenli** [comment]
I finished the dashboard UI design, which is responsive across different devices (mobile, tablet, and desktop), providing a consistent user experience. It ensures compatibility across modern browsers, including Chrome, Firefox, Safari, and others.

Live sensor data is displayed on the dashboard, and it refreshes every 10 seconds. The data includes temperature, humidity, and soil moisture levels.
