### ISSUE TITLE
Use Case 7 : Onboard New Team Members

### ISSUE THREAD

**Issue by ktageja** [ktageja/DataSense-PRJ666-team-5#9]
## User Story
As a new team member, I want to understand the project’s goals, architecture, and my responsibilities so that I can contribute effectively to the project.
## Description
This use case describes how new team members are onboarded and trained to understand the project, its architecture, and their role within the team.

New team members must be brought up to speed on the project, including technical aspects, workflows, and team processes, to ensure smooth collaboration and efficient progress.

## Acceptance Criteria

- [x] New team members receive a project overview (goals, architecture, milestones).
- [x]  New members are introduced to the project’s tools (GitHub, CI/CD, communication tools).
- [x]  Each new team member is assigned a mentor for support.
- [x]  New members review documentation and attend standup meetings to get familiar with ongoing tasks.
- [x]  New team members are able to start contributing to the project within a reasonable timeframe (e.g., after the first week).

### Normal Flow of Events
Team lead or project manager provides an overview of the project to new members (e.g., goals, architecture, key milestones).
New team members are introduced to the tools used in the project (e.g., GitHub, CI/CD, task management, communication channels).
Team lead assigns a mentor or buddy from the team to help the new member.
The new team member reviews project documentation (e.g., SRS, architecture diagrams, workflows).
New members attend a team standup meeting to get familiar with the current tasks.
New team members start working on a small task or review existing work to understand the project workflow.

### S-1:   New team member has trouble understanding the project
The new team member struggles to grasp the project's complexity.
The mentor/buddy provides additional support, including walkthroughs or technical sessions.

### S-2:  Lack of documentation or resources
The new team member finds that some key project documentation is outdated or missing.
The team lead ensures documentation is updated or assigns a team member to fill the gaps.

**Comment by arilloid** [comment]
## Issue Closed
New team members have been onboarded. They are familiarized with the project and are able to contribute to it.
